version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
commands:
  git_checkout_from_cache:
    description: "Git checkout and save cache"
    steps:
      - restore_cache:
          name: Git restore cache
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - run:
          name: Fetch git tags
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ== ' >> ~/.ssh/known_hosts
            # Fetch tags if git cache is present
            if [ -e /home/circleci/project/.git ]
            then
              git fetch origin --tags
            fi
      - checkout
      - run:
          name: Compress git objects
          command: git gc
      - save_cache:
          name: Git save cache
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  npm_install:
    description: "Install npm modules"
    steps:
      - run:
          name: Bootstrap
          command: npm run bootstrap

  build:
    description: "Build"
    steps:
      - run:
          name: "build packages"
          command: npm run build:local
      - run:
          name: "build core"
          command: node_modules/lerna/cli.js exec --scope @deriv/core -- npm run build

  npm_deploy_folder:
    description: "Deploy to Test Link"
    steps:
      - run:
          name: "Run deploy:folder"
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            npm run deploy:folder br_${CIRCLE_BRANCH}

  docker:
    description: "Build and Push image to docker hub"
    steps:
      - setup_remote_docker
      - run:
          name: Building docker image
          command: |
            docker build -t ${DOCKHUB_ORGANISATION}/deriv-app:${CIRCLE_TAG} .
      - run:
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/deriv-app:${CIRCLE_TAG}
  k8s_deploy_staging:
    description: "Deploy to k8s cluster"
    steps:
      - k8s/install-kubectl
      - run:
          name: Deploying to k8s cluster for service deriv-app
          command: |
            echo $CA_CRT | base64 --decode > ca.crt
            kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN set image deployment/staging-deriv-app staging-deriv-app=${DOCKHUB_ORGANISATION}/deriv-app:${CIRCLE_TAG}

  k8s_deploy_production:
    description: "Deploy to k8s cluster"
    steps:
      - k8s/install-kubectl
      - run:
          name: Deploying to k8s cluster for service deriv-app
          command: |
            echo $CA_CRT | base64 --decode > ca.crt
            kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN set image deployment/production-deriv-app production-deriv-app=${DOCKHUB_ORGANISATION}/deriv-app:${CIRCLE_TAG}


jobs:
  release_staging:
    docker:
      - image: circleci/node:11.15.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - build
      - docker
      - k8s_deploy_staging

  release_production:
    docker:
      - image: circleci/node:11.15.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - build
      - docker
      - k8s_deploy_production

  deploy_test_branch:
    docker:
      - image: circleci/node:11.15.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - npm_deploy_folder

workflows:
  deploy_test_branch:
    jobs:
      - deploy_test_branch:
          filters:
            branches:
              ignore: /dev|master/
  release_staging:
    jobs:
      - release_staging:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^staging.*/
  release_production:
    jobs:
      - release_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/

